name: Test Godot Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - uses: MikeSchulze/gdUnit4-action@v1.1.1
      with:
        godot-version: '4.2.2'
        paths: 'res://test'
        upload-report: false
        publish-report: false
        project_dir: ./src/
